/**
 * real_world_scenarios.test.js
 * Tier 4: Real-World Application Scenarios
 * Simulates complete end-to-end B2B Umrah agency workflows:
 * Scenario 1: Complete Umrah Package Billing & Ledger Settlement Cycle
 * Scenario 2: Sub-Agency User Lifecycle & Audited Voucher Posting
 * Scenario 3: Multi-Voucher Sequential Billing & Statement Reconciliation
 */

const { describe, it, before, after } = require('node:test');
const assert = require('node:assert/strict');
const { startTestServer, stopServer, apiRequest, loginAs } = require('../helpers/serverControl');
const { CANONICAL_BD_AGENT, CANONICAL_SAUDI_AGENT, createVoucherPayload } = require('../helpers/fixtures');

describe('Tier 4: Real-World Application Scenarios', () => {
  before(async () => {
    await startTestServer();
  });

  after(async () => {
    await stopServer();
  });

  it('T4-SCENARIO-01: Complete Umrah Package Billing & Ledger Settlement Cycle', async () => {
    // 1. Super Admin Login
    const { token, user } = await loginAs('admin', 'admin');
    assert.ok(token, 'Admin must authenticate successfully');
    assert.strictEqual(user.role, 'Super Admin');

    // 2. Fetch Agent Directory to locate target BD and Saudi agents
    const agentsRes = await apiRequest('GET', '/api/agents', null, {
      Authorization: `Bearer ${token}`
    });
    assert.strictEqual(agentsRes.status, 200, 'Must retrieve agent directory');
    const bdAgent = agentsRes.data.data.find(
      (a) => a.id === CANONICAL_BD_AGENT.id || a._id === CANONICAL_BD_AGENT.id
    );
    assert.ok(bdAgent, 'BD Sub-agency must exist in database');
    const saudiAgent = agentsRes.data.data.find(
      (a) => a.id === CANONICAL_SAUDI_AGENT.id || a._id === CANONICAL_SAUDI_AGENT.id
    );
    assert.ok(saudiAgent, 'Saudi supplier must exist in database');

    const startBalance = bdAgent.currentBalance || 0;

    // 3. Compose realistic 4-Pax Umrah Package Voucher:
    //    - 4 Visa: 4 * 300 SAR = 1200 SAR (BDT 39,000)
    //    - Makkah Hotel: 1200 SAR (BDT 39,000)
    //    - Madinah Hotel: 800 SAR (BDT 26,000)
    //    - Transport: 500 SAR (BDT 16,250)
    //    - BRN: 200 SAR (BDT 6,500)
    //    Total Billable: BDT 126,750
    //    Payment Received: BDT 50,000 (Cash in hand)
    //    Net Due Added to Ledger: BDT 76,750
    const grossBDT = 126750;
    const paymentBDT = 50000;
    const netDueAdded = grossBDT - paymentBDT;
    const passengerGroupRef = `AL-HAJJI GROUP (${Date.now()})`;

    const voucherPayload = createVoucherPayload({
      createdBy: user.username,
      bdAgentId: bdAgent.id || bdAgent._id,
      saudiAgentId: saudiAgent.id || saudiAgent._id,
      passengerRef: passengerGroupRef,
      nowPaying: paymentBDT,
      totals: {
        grossAmountSAR: 3900,
        grossAmountBDT: grossBDT,
        paidAmountBDT: paymentBDT,
        netDueAdded,
        dueAdjustment: 0,
        totalBillable: grossBDT
      },
      paymentReceived: {
        mode: 'Recv IN HAND (BDT)',
        amountBDT: paymentBDT,
        trxId: `CASH-${Date.now()}`
      }
    });

    // 4. Submit Voucher to /api/entries/batch
    const postRes = await apiRequest('POST', '/api/entries/batch', voucherPayload, {
      Authorization: `Bearer ${token}`
    });
    assert.strictEqual(postRes.status, 201, 'Voucher posting must return 201');
    const createdVoucher = postRes.data.data.billingDoc;
    assert.ok(createdVoucher, 'Must return created voucher');
    assert.ok(createdVoucher.voucherNo, 'Voucher must have sequential voucherNo');
    assert.strictEqual(createdVoucher.totalBillable, grossBDT, 'Voucher totalBillable must match gross');
    assert.strictEqual(createdVoucher.nowPaying, paymentBDT, 'Voucher nowPaying must match payment');

    // 5. Query Ledger Statement for this BD Sub-Agency
    const targetAgentId = bdAgent.id || bdAgent._id;
    const statementRes = await apiRequest(
      'GET',
      `/api/ledgers?agentId=${encodeURIComponent(targetAgentId)}&limit=500`,
      null,
      { Authorization: `Bearer ${token}` }
    );
    assert.strictEqual(statementRes.status, 200, 'Must retrieve agent ledger statements');
    const statementEntries = statementRes.data.data || [];

    // Find the ledger entries generated by this voucher
    const billRow = statementEntries.find(
      (e) => (e.reference === createdVoucher.voucherNo || e.gCode === createdVoucher.voucherNo)
        && e.transactionType === 'VOUCHER_BILL'
    );
    assert.ok(billRow, 'Ledger must contain VOUCHER_BILL entry with matching voucherNo reference');
    assert.strictEqual(billRow.debit, grossBDT, 'VOUCHER_BILL debit must equal totalBillable');

    const paymentRow = statementEntries.find(
      (e) => (e.reference === createdVoucher.voucherNo || e.gCode === createdVoucher.voucherNo)
        && e.transactionType === 'PAYMENT_RECEIVED'
    );
    assert.ok(paymentRow, 'Ledger must contain PAYMENT_RECEIVED entry with matching voucherNo reference');
    assert.strictEqual(paymentRow.credit, paymentBDT, 'PAYMENT_RECEIVED credit must equal nowPaying');

    // 6. Verify BD Agent Balance was updated atomically
    const agentsAfterRes = await apiRequest('GET', '/api/agents', null, {
      Authorization: `Bearer ${token}`
    });
    const updatedBdAgent = agentsAfterRes.data.data.find(
      (a) => a.id === bdAgent.id || a._id === bdAgent._id
    );
    const expectedFinalBalance = startBalance + netDueAdded;
    assert.strictEqual(
      updatedBdAgent.currentBalance,
      expectedFinalBalance,
      `Agent current balance must equal start balance + net due. Expected: ${expectedFinalBalance}, Got: ${updatedBdAgent.currentBalance}`
    );
  });

  it('T4-SCENARIO-02: Sub-Agency User Lifecycle & Audited Voucher Posting', async () => {
    const timestamp = Date.now();
    const staffUser = {
      username: `staff_audit_${timestamp}`,
      password: `Pass_${timestamp}!`,
      role: 'Staff',
      name: `Audit Staff ${timestamp}`
    };

    // 1. User Registration
    const regRes = await apiRequest('POST', '/api/auth/register', staffUser);
    assert.strictEqual(regRes.status, 201, 'Staff registration must succeed');

    // 2. Staff Authentication
    const loginRes = await apiRequest('POST', '/api/auth/login', {
      username: staffUser.username,
      password: staffUser.password
    });
    assert.strictEqual(loginRes.status, 200, 'Staff login must succeed');
    const staffToken = loginRes.data.token;
    assert.ok(staffToken);

    // 3. Verify Profile
    const meRes = await apiRequest('GET', '/api/auth/me', null, {
      Authorization: `Bearer ${staffToken}`
    });
    assert.strictEqual(meRes.status, 200);
    assert.strictEqual(meRes.data.user.username, staffUser.username);

    // 4. Staff posts an Umrah voucher with user attribution
    const staffVoucherPayload = createVoucherPayload({
      createdBy: staffUser.username,
      passengerRef: `STAFF-BOOKING-${timestamp}`
    });

    const postRes = await apiRequest('POST', '/api/entries/batch', staffVoucherPayload, {
      Authorization: `Bearer ${staffToken}`
    });
    assert.strictEqual(postRes.status, 201, 'Voucher posted by staff must succeed');

    // 5. Staff Logout
    const logoutRes = await apiRequest('POST', '/api/auth/logout');
    assert.strictEqual(logoutRes.status, 200);

    // 6. Verify unauthenticated access fails
    const lockedRes = await apiRequest('GET', '/api/auth/me');
    assert.strictEqual(lockedRes.status, 401, 'Unauthenticated call must be locked with 401');
  });

  it('T4-SCENARIO-03: Multi-Voucher Sequential Billing & Statement Reconciliation', async () => {
    const { token } = await loginAs('admin', 'admin');

    // Fetch BD Agent
    const agentsRes = await apiRequest('GET', '/api/agents', null, {
      Authorization: `Bearer ${token}`
    });
    const bdAgent = agentsRes.data.data.find(
      (a) => a.id === CANONICAL_BD_AGENT.id || a._id === CANONICAL_BD_AGENT.id
    );

    // Post Voucher 1: Bill 30,000, Pay 10,000 -> net +20,000
    const v1 = createVoucherPayload({
      passengerRef: `SEQ-VOUCHER-1-${Date.now()}`,
      nowPaying: 10000,
      totals: {
        grossAmountSAR: 300,
        grossAmountBDT: 30000,
        paidAmountBDT: 10000,
        netDueAdded: 20000,
        dueAdjustment: 0,
        totalBillable: 30000
      },
      paymentReceived: { mode: 'Recv IN HAND (BDT)', amountBDT: 10000, trxId: `T1-${Date.now()}` }
    });
    const res1 = await apiRequest('POST', '/api/entries/batch', v1, {
      Authorization: `Bearer ${token}`
    });
    assert.strictEqual(res1.status, 201);

    // Post Voucher 2: Bill 40,000, Pay 40,000 -> net 0
    const v2 = createVoucherPayload({
      passengerRef: `SEQ-VOUCHER-2-${Date.now()}`,
      nowPaying: 40000,
      totals: {
        grossAmountSAR: 400,
        grossAmountBDT: 40000,
        paidAmountBDT: 40000,
        netDueAdded: 0,
        dueAdjustment: 0,
        totalBillable: 40000
      },
      paymentReceived: { mode: 'Recv IN HAND (BDT)', amountBDT: 40000, trxId: `T2-${Date.now()}` }
    });
    const res2 = await apiRequest('POST', '/api/entries/batch', v2, {
      Authorization: `Bearer ${token}`
    });
    assert.strictEqual(res2.status, 201);

    // Fetch Statement and audit ledger continuity
    const targetAgentId = bdAgent.id || bdAgent._id;
    const stmtRes = await apiRequest(
      'GET',
      `/api/ledgers?agentId=${encodeURIComponent(targetAgentId)}&limit=500`,
      null,
      { Authorization: `Bearer ${token}` }
    );
    assert.strictEqual(stmtRes.status, 200);
    const ledger = stmtRes.data.data;
    assert.ok(Array.isArray(ledger) && ledger.length >= 4, 'Must have recorded sequential entries');

    // Audit double-entry arithmetic across all entries for this agent
    for (let i = 1; i < ledger.length; i++) {
      const prev = ledger[i - 1];
      const curr = ledger[i];
      const debit = Number(curr.debit) || 0;
      const credit = Number(curr.credit) || 0;
      const expectedBal = prev.runningBalance + debit - credit;

      assert.strictEqual(
        curr.runningBalance,
        expectedBal,
        `Ledger integrity check failed at index ${i}: expected ${expectedBal}, got ${curr.runningBalance}`
      );
    }
  });
});
